title = "chess game analysis"
type = "article"
author = "64f3b48024172b1dd01da6ac25fe39b3b86fc123"
issue = "4"
date = "a date idk"
description = "a very normal chess game"
path = "chessgameanalysis.html"
