title = "psychosocial rock paper scissors"
type = "article"
author = "9616a8146dd7a21781efef42e861756c0b490217"
issue = "1"
date = "ah"
description = "wah"
path = "APsychosocialApproachtoGameTheoreticAnalysiso.html"
