title = "The Grass is Greyer on the Other Side "
type = "article"
author = "9616a8146dd7a21781efef42e861756c0b490217"
issue = "2"
date = "wah"
description = "wah"
path = "TheGrassisGreyerontheOtherSideJasminePapinoWo.html"
